#!/bin/bash

x=$(xinput --list --id-only 'ELAN1200:00 04F3:3044 Touchpad')

y=$(xinput list-props $x | grep Enabled)

dev_status=${y:22}

if [ $dev_status = 0 ]; then
	xinput enable $x
	echo "Touchpad acceso."
else
	xinput disable $x
	echo "Touchpad spento."
fi
